openapi: 3.0.0
info:
  description: "これは研修用のTODOリストに関するAPIです。"
  version: "1.0.0"
  title: "TODO LIST API"
  termsOfService: "http://swagger.io/terms/"
paths:
  /tasks{option}:
    get:
      summary: "タスクの取得"
      description: "optionで指定されたタスクを返却します"
      parameters:
        - name: "data"
          in: "query"
          schema:
            type: "object"
            properties:
              todo:
                type: "boolean"
                description: "trueの時未完了のタスクを返却する"
                example: true
                default: true
              done:
                type: "boolean"
                description: "trueの時完了済みのタスクを返却する"
                example: true
                default: true
              sort:
                type: "string"
                example: "limit"
                description: "ソート順\n[start]:タスク開始日\n[linmit]:期限日\n[title]:タスク名"
                enum:
                  - "start"
                  - "limit"
                  - "title"
                default: limit
              order:
                type: "string"
                example: "ac"
                description: "ソート方向\n[ac]:昇順 [de]:降順"
                enum:
                  - "de"
                  - "ac"
                default: "de"
              number:
                type: "integer"
                description: "表示件数"
                example: 20
                default: 20
              search:
                type: "string"
                description: "タスク名の検索"
                example: ""
      responses:
        "200":
          description: "成功時のレスポンス"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  required:
                    - id
                    - title
                    - start
                    - limit
                    - memo
                    - status
                  properties:
                    id:
                      type: "string"
                      description: "タスクの一意なID"
                      example: "202001011234"
                    title:
                      type: "string"
                      description: "タスクのタイトル"
                      example: "タスクのタイトル"
                    start:
                      type: "string"
                      description: "タスクの開始日"
                      example: "2020/01/01"
                    limit:
                      type: "string"
                      description: "タスクの期限日"
                      example: "9999/12/31"
                    memo:
                      type: "string"
                      description: "タスクのメモ"
                      example: "タスクのメモ"
                    status:
                      type: boolean
                      description: "タスクのステータス trueの時未完了"
                      example: true
