openapi: 3.0.0
info:
  description: "これは研修用のTODOリストに関するAPIです。"
  version: "1.0.0"
  title: "TODO LIST API"
  termsOfService: "http://swagger.io/terms/"
paths:
  /tasks:
    get:
      summary: "タスクの取得"
      description: "optionで指定されたタスクを返却します"
      parameters:
        - name: todo
          in: "query"
          description: "trueの時未完了のタスクを返却する"
          schema:
            type: boolean
            default: true
            example: true
        - name: done
          in: "query"
          description: "trueの時完了済みのタスクを返却する"
          schema:
            type: boolean
            example: true
            default: true
        - name: sort
          in: "query"
          description: "ソート順<br/>[start]:タスク開始日<br/>[limit]:期限日<br/>[title]:タスク名"
          schema:
            type: string
            example: "limit"
            enum: [start, limit, title]
            default: limit
        - name: order
          in: "query"
          description: "ソート方向\n<br />[ac]:昇順 <br>[de]:降順"
          schema:
            type: string
            example: "ac"
            enum: ["de", "ac"]
            default: "de"
        - name: number
          in: "query"
          description: "表示件数"
          schema:
            type: integer
            example: 20
            default: 20
        - name: search
          in: "query"
          description: "タスク名の検索"
          schema:
            type: "string"
            default: ""
            example: ""
      responses:
        "200":
          description: "成功時のレスポンス"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  required:
                    - id
                    - title
                    - start
                    - limit
                    - memo
                    - status
                  properties:
                    id:
                      type: "string"
                      description: "タスクの一意なID"
                      example: "202001011234"
                    title:
                      type: "string"
                      description: "タスクのタイトル"
                      example: "タスクのタイトル"
                    start:
                      type: "string"
                      description: "タスクの開始日"
                      example: "2020/01/01"
                    limit:
                      type: "string"
                      description: "タスクの期限日"
                      example: "9999/12/31"
                    memo:
                      type: "string"
                      description: "タスクのメモ"
                      example: "タスクのメモ"
                    status:
                      type: boolean
                      description: "タスクのステータス trueの時未完了"
                      example: true
  /create/task:
    post:
      summary: "タスクの追加"
      requestBody:
        description: "新しいタスクを追加します"
        content:
          application/json:
            schema:
              type: object
              required:
                - id
                - title
                - start
                - limit
              properties:
                id:
                  type: string
                  description: "タスクの一意のID"
                title:
                  type: string
                  description: "タスクのタイトル"
                start:
                  type: string
                  description: "タスクの開始日YYYY/MM/DD"
                limit:
                  type: string
                  description: "タスクの期限日YYYY/MM/DD"
                memo:
                  type: string
                  description: "タスクの詳細"

      responses:
        "200":
          description: "登録成功"
        "400":
          description: "Bad Request"
        "409":
          description: "登録失敗"
  /update/task:
    post:
      summary: "タスクの更新"
      requestBody:
        description: "タスクを更新します"
        content:
          application/json:
            schema:
              type: object
              required:
                - id
                - title
                - start
                - limit
                - memo
              properties:
                id:
                  type: string
                  description: "タスクの一意のID"
                title:
                  type: string
                  description: "タスクのタイトル"
                start:
                  type: string
                  description: "タスクの開始日YYYY/MM/DD"
                limit:
                  type: string
                  description: "タスクの期限日YYYY/MM/DD"
                memo:
                  type: string
                  description: "タスクの詳細"

      responses:
        "200":
          description: "更新成功"
        "400":
          description: "Bad Request"
        "409":
          description: "更新の失敗"
  /update/status:
    post:
      summary: "ステータスの更新"
      requestBody:
        description: "ステータスを更新します"
        content:
          application/json:
            schema:
              type: object
              required:
                - id
                - status
              properties:
                id:
                  type: string
                  description: "タスクの一意のID"
                status:
                  type: boolean
                  description: "タスクのステータス<br>[true]:完了<br>[false]:未完了"
      responses:
        "200":
          description: "更新成功"
        "400":
          description: "Bad Request"
        "409":
          description: "更新の失敗"
  /delete/task:
    post:
      summary: "タスクの削除"
      requestBody:
        description: "タスクを削除します"
        content:
          application/json:
            schema:
              type: object
              required:
                - id
              properties:
                id:
                  type: string
                  description: "タスクの一意のID"
      responses:
        "200":
          description: "削除成功"
        "409":
          description: "更新の失敗"
